### ISSUE TITLE
CRD isn't removable

### ISSUE THREAD

**Issue by alter** [storageos/charts#101]
Issue:
I've setup storageos using official documentation.(kubernetes 1.16.6)
After I've tried to remove it, but it was unsuccessful, b/c it can't remove CRD, even with your github command:
`kubectl -n storageos-operator delete storageoscluster storageos`

Solution:
`kubectl -n storageos-operator patch crd storageosclusters.storageos.com  -p '{"metadata":{"finalizers":[]}}' --type=merge`

You have to fix finalizers for CRD.

**Comment by avestuk** [comment]
@alter Was the StorageOS Operator running when you deleted the StorageOSCluster resource?
