### ISSUE TITLE
Starting Path of Nodes used Space?

### ISSUE THREAD

**Issue by gelinger777** [storageos/charts#26]
I have a very beginner question. So excuse me for being trivial. In my kubernetes cluster  I want to use storageOS. But I want to understand following. How to tell StorageOS to use as a space specific mount points . I am using Hetzner Cloud Nodes as Kubernetes Nodes, and in 2 worker nodes I have mounted volumes  on /mnt/node_data   and I want StorageOS to explicitly use those mounted volumes (or directory path) as space ... Is that possible? And would StorageOS created volume be fast enough to  use as  MySQL data directory folder for mariadb helm ? 
Thank you.

**Comment by avestuk** [comment]
Hi @gelinger777, 

The short answer is that it is entirely possible to control what disks StorageOS uses and in fact using multiple devices allows StorageOS to load balance writes across the devices. Furthermore, StorageOS was designed to provide persistent storage to applications that require high performance, such as databases and messaging queues so your MariaDB use case is a great fit. 

Please see our documentation about how to [Manage Host Storage ](https://docs.storageos.com/docs/operations/managing-host-storage) for how to specify which disks StorageOS will use. If you have any further questions feel free to contact us on our [public slack channel](https://slack.storageos.com)

Alex.

**Comment by gelinger777** [comment]
@avestuk  does the same structure apply also in case of Kubernetes Cluster? 
I saw that in docs you recommend to mound the external hdd to dev2 in storageos data folder. What if I will mount it to dev1 ? would then explicitly the external hdd used?

**Comment by avestuk** [comment]
@gelinger777 the structure is the same for Kubernetes nodes. 

If you want to just use a single device then you can mount the device to /var/lib/storageos 

It is currently not possible to mount multiple devices for StorageOS to use for storage and specify which device to use for what volumes.
