### ISSUE TITLE
storageos chart does not install and storageos-operator not provisioning

### ISSUE THREAD

**Issue by staticdev** [storageos/charts#60]
I am following the README-CSI and when I am using helm-v2.14.0-linux-amd64 in a single-node kubeadm (1.14.2). I did a `helm init && helm repo add storageos https://charts.storageos.com && helm repo update`. After that, I search for storageos and I see it: 

```
helm search storageos/storageos
NAME                               	CHART VERSION	APP VERSION	DESCRIPTION
storageos/storageos                	1.1.0        	1.2.1      	Converged storage for containers
storageos/storageos-operator       	0.1.1        	1.1.0      	Cloud Native storage for containers
storageos/storageoscluster-operator	1.0.3        	1.1.0      	A StorageOS Cluster Operator chart for Kubernetes
```

Then, if I try to install it, I get error: 

```
helm install storageos/storageos --namespace storageos --set cluster.join=node1 --set csi.enable=true
Error: no available release name found
```
Also, if I create a ServiceAccount for Helm and try the same command, I get the error:

```
Error: validation failed: error validating "": error validating data: [ValidationError(CustomResourceDefinition.status): missing required field "conditions" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionStatus, ValidationError(CustomResourceDefinition.status): missing required field "storedVersions" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionStatus]
```

Is this a bug?

**Comment by darkowlzz** [comment]
Hi,
Thanks for trying the chart and reporting the issue.

We test all the charts in our CI with k8s 1.14.2 and helm 2.13, and they all seem to be working fine. See [CI logs](https://travis-ci.org/storageos/charts/builds/534788373#L295) for reference.

The release name issue seems to be helm command issue, maybe related to the tiller. You can pass a release name explicitly if needed with `--name <release-name>`.

It could be that the tiller is not setup properly in your cluster. You can follow what we do in our CI environment https://github.com/storageos/charts/blob/master/test/e2e.sh#L104-L106.

Also, we recommend using the [operator chart](https://github.com/storageos/charts/tree/master/stable/storageos-operator), which is well maintained, instead of installing this chart, which will be deprecated in the future.

Hope that helps.

**Comment by staticdev** [comment]
@darkowlzz The operator chart documentation is not very clear.. Does this "Most installations will want to use the default CSI driver. To use the Native Driver instead, disable CSI" means this chart uses CSI driver by default?

**Comment by darkowlzz** [comment]
Yes, `cluster.csi.enable` is `true` by default https://github.com/storageos/charts/blob/master/stable/storageos-operator/values.yaml#L93. So CSI is the default mode. You don't need to change anything.

You can learn more about the operator with examples here https://docs.storageos.com/docs/reference/cluster-operator/ .

**Comment by staticdev** [comment]
Excelent, I will try it out later and give you a feedback.

**Comment by staticdev** [comment]
@darkowlzz now storageos is installed but it is not provisioning any PV. I created some PVCs to test with PODs associated to it. Isn't dynamic provisioning also enabled by default?

**Comment by darkowlzz** [comment]
Can you share your PVC manifest?
I'm looking for `spec.storageClassName` value of the PVC.

I just tested it myself with the latest version of chart and I'm able to provision PVC and binding works as well.

**Comment by staticdev** [comment]
Here is one example of PVC used, no storageClassName is specified beforehand.

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: mongo-claim0
  name: mongo-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
```

I saw a StorageClass named 'fast' was created by default.

After patching it with `is-default-class` annotation, it started provisiong PVs:

>   kubectl patch storageclass fast -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'

**Comment by croomes** [comment]
Looks like this was resolved?  Pls re-open if not.
