### ISSUE TITLE
Questions regarding installing StorageOS on Kubernetes

### ISSUE THREAD

**Issue by avarf** [storageos/charts#88]
As the title says this is not an issue but it is some questions that I will be thankful if you answer.

We have a small in house k8s cluster running on bare metal and we are running different versions of our platform (which consists of many components) on it and each on a different namespace.
1. If I want to use StorageOS do I need to install one StorageOS in each namespace of StorageOS works per cluster? For example, we have a Prometheus + grafana stack which are running in their own namespace and they gather information from the whole cluster.
2. Does your Helm chart compatible with k8s v 1.16? Probably as you know there were many changes in the newest k8s API and most of the older charts need to adapt to these changes.

Thank you.

**Comment by Arau** [comment]
Hi @avarf,

> 1. If I want to use StorageOS do I need to install one StorageOS in each namespace of StorageOS works per cluster? For example, we have a Prometheus + grafana stack which are running in their 
own namespace and they gather information from the whole cluster.

StorageOS runs per Kubernetes Cluster. Through the Helm installation, it will run in the kube-system NameSpace by default. However, you can choose at the installation time where the StorageOS Pods will be installed, for instance the storageos namespace. 

The only thing you have to do once the StorageOS cluster is running is to reference the StorageClass belonging to StorageOS, by default called "fast" to use StorageOS Volumes. You can for instance, use the Prometheus Operator to deploy the StatefulSet using the fast StorageClass. Check this out https://github.com/storageos/deploy/tree/master/k8s/examples/prometheus, or https://docs.storageos.com/docs/usecases/kubernetes/.


> 2. Does your Helm chart compatible with k8s v 1.16? Probably as you know there were many changes in the newest k8s API and most of the older charts need to adapt to these changes.
> 
> Thank you.

The Charts have been adapted to work with the API changes related to 1.16.

**Comment by avarf** [comment]
Thank you for your quick reply.
