### ISSUE TITLE
storageos-operator chart not working with helm3

### ISSUE THREAD

**Issue by iomarcovalente** [storageos/charts#92]
Attempting to deploy storageos on an EKS cluster with helm v3.0.0 fails.

Please find logs output below:
```
maeg9@test ~/Documents/git/k8s/storageos -  (29_storage-os-implementation) $ helm3 install release-name storageos/storageos-operator --namespace storageos
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "StorageOSCluster" in version "storageos.com/v1"
```

Could you recommend what is best course of action in this case please? 

Would templating the chart locally and apply to my cluster work fine or is this chart dependant on Helm hooks (I am referring to the crd and post-delete ones)?

**Comment by iomarcovalente** [comment]
Reason was due to `crds` hooks being still used. To get this to work for helm3 move those resources, namely:
- `job_crd.yaml`
- `nfsserver_crd.yaml`
- `storageoscluster_crd.yaml`
- `storageosupgrade_crd.yaml`
to a folder called `crds` at the same level of the `template` folder.
Reference https://github.com/helm/helm/issues/6665

**Comment by croomes** [comment]
Hi @iomarcovalente, thanks for raising this (and finding the solution!)

We haven't tested with Helm 3 yet but happy to hear you got it going with the workaround.  We'll give it a go ourselves and update the chart.
